version: "3.9"
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=kafka
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
  spark-master:
    image: bitnami/spark:latest
    environment:
      - SPARK_MODE=master
    ports:
      - "7077:7077"
      - "8080:8080"
    volumes:
      - ./metrics:/app/metrics
  spark-worker-main:
    image: bitnami/spark:latest
    depends_on:
      - spark-master
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
    ports:
      - "8081:8081"
  spark-worker:
    image: bitnami/spark:latest
    depends_on:
      - spark-master
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
  mock-data:
    build:
      context: ./mock-data
    ports:
      - "9998:9998"
    depends_on:
      - kafka
  spark-app:
    build:
      context: ./spark-app
    depends_on:
      - spark-master
      - mock-data
    environment:
      - SPARK_MODE=client
    user: root
    command: >
      /opt/bitnami/spark/bin/spark-submit
      --master spark://spark-master:7077
      /app/spark-stream.py
    volumes:
      - ./metrics:/app/metrics
  flink-app:
    build:
      context: ./flink-app
    depends_on:
      - kafka
    environment:
      - FLINK_MODE=application
    volumes:
      - ./metrics:/app/metrics

networks:
  default:
    name: my-network
    driver: bridge
