FROM flink:1.18-scala_2.12

# Install PyFlink and dependencies
RUN apt-get update && apt-get install -y python3 python3-pip
RUN ln -s /usr/bin/python3 /usr/bin/python
RUN pip install apache-flink==1.18.1 psutil statistics

# Set working directory
WORKDIR /app

# copy the job script 
COPY flink-stream.py /app/flink-stream.py

# Set entrypoint to run the PyFlink job
CMD ["flink", "run", "-py", "flink-stream.py"]
