FROM flink:1.18-scala_2.12

# Install PyFlink
RUN apt-get update && apt-get install -y python3 python3-pip
RUN ln -s /usr/bin/python3 /usr/bin/python
RUN pip install apache-flink==1.18.1

# Set working directory
WORKDIR /app

# Copy the flink job
COPY flink-stream.py .

# Set entrypoint to run the PyFlink job
CMD ["flink", "run", "-py", "flink-stream.py"]
