FROM python:3.10-slim
# Install Java and Flink dependencies
RUN apt-get update && apt-get install -y openjdk-11-jre && apt-get clean
# Install PyFlink
RUN pip install apache-flink
# Set working directory
WORKDIR /app
# Copy the flink job
COPY flink-stream.py .
# Set entrypoint
CMD ["python", "flink-stream.py"]
