FROM python:3.10-slim 
#what python is used
WORKDIR /app
#sets the directory to app 
COPY mock-stream-server.py .
#copies my file into app folder
CMD ["python", "mock-stream-server.py"]
#what to run when it starts